services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Oveleon\ContaoBeFieldDependency\:
        resource: ../../
        exclude: ../../{ContaoManager,Model,Resources}
